#!/bin/sh 


# Program: update_test_cases.sh
# Description: This script updates test cases with 
#   the autogenerated output from generate-test-checks.py.
#
# Required Programs:
#   - cargo: For updating the rust dependencies
#   - python3: For running the script
#
# Usage: LLZKLIB_HOME=path/to/llzk-lib ./scripts/update_test_cases.sh test1.circom [test2.circom ...]

set -e

if [ -z $LLZKLIB_HOME ]; then 
  echo "Set environment variable LLZKLIB_HOME with the path to llzk-lib"
  exit 1
fi

if ! test -z "$(git status --porcelain)"; then 
  echo "Git index is dirty. Run this script on a clean index"
  exit 1
fi

for f in $@; do 
  o=$(mktemp -d)
  name=$(basename "$f" .circom)
  cargo run -p circom -- --llzk templated -o $o "$f" 
  sed '/\/\/ CHECK-*/d' "$f" > "$f".updated
  python3 $LLZKLIB_HOME/scripts/generate-test-checks.py "$o/${name}_llzk/$name.llzk" | grep '^// CHECK-' >> "$f".updated 
  mv "$f".updated "$f"
done
