#!/bin/sh

# Program: update_test_cases.sh [--concrete]
# Description: This script updates test cases with
#   the autogenerated output from generate-test-checks.py.
#   Uses '--llzk templated' by default unless the '--concrete' flag is specified,
#   in which case '--llzk concrete' is passed to circom.
#
# Required Programs:
#   - cargo: For building and running the frontend
#   - python3: For running the script
#
# Usage: LLZKLIB_HOME=path/to/llzk-lib ./scripts/update_test_cases.sh test1.circom [test2.circom ...]

set -e

llzk_type=templated

# Parse flags without touching positional args.
positional=""
while [ $# -gt 0 ]; do
  case "$1" in
    --concrete)
      llzk_type=concrete
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      positional="$positional $1"
      shift
      ;;
  esac
done
positional="$positional $@"

if [ -z $LLZKLIB_HOME ]; then
  echo "Set environment variable LLZKLIB_HOME with the path to llzk-lib"
  exit 1
fi

if ! test -z "$(git status --porcelain)"; then
  echo "Git index is dirty. Run this script on a clean index"
  exit 1
fi

# Build the frontend once 
cargo build -p circom

for f in $positional; do
  o=$(mktemp -d)
  name=$(basename "$f" .circom)
  target/debug/circom --stabilize --llzk_plaintext --llzk "$llzk_type" -o $o "$f"
  sed '/\/\/ CHECK-*/d' "$f" > "$f".updated
  python3 $LLZKLIB_HOME/scripts/generate-test-checks.py "$o/${name}_llzk/$name.llzk" | grep '^// CHECK-' >> "$f".updated
  mv "$f".updated "$f"
done
