[package]
name = "llzk_backend"
version = "0.1.0"
authors = ["Veridise"]
edition = "2018"

[dependencies]
program_structure = { path = "../program_structure" }
ansi_term = "0.12.1"
anyhow = "1.0"
num-bigint-dig = "0.8.4"
num-traits = "0.2.6"
mlir-sys = "0.5.0"
melior = { version = "0.25", features = ["ods-dialects"] }
melior-macro = "0.18"
llzk = { git = "https://github.com/Veridise/llzk-rs", package = "llzk" }
