# These format settings only apply when calling format from within this module.
# If called from the top level, the top-level settings will apply.
use_small_heuristics = "Max"
max_width = 100
wrap_comments = true
normalize_comments = true
comment_width = 100
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
